### ISSUE TITLE
I Run The Bot And Err

### ISSUE THREAD

**Issue by ggkk77121** [v-Cx/Discord-Account-Generator#7]
/home/runner/Bot/node_modules/discord.js/src/client/Client.js:548
      throw new TypeError('CLIENT_MISSING_INTENTS');
      ^

TypeError [CLIENT_MISSING_INTENTS]: Valid intents must be provided for the Client.
    at Client._validateOptions (/home/runner/Man/node_modules/discord.js/src/client/Client.js:548:13)
    at new Client (/home/runner/Man/node_modules/discord.js/src/client/Client.js:76:10)
    at Object.<anonymous> (/home/runner/Man/server.js:8:13)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47 {
  [Symbol(code)]: 'CLIENT_MISSING_INTENTS'
}

Node.js v17.3.1
exit status 1

**Comment by v-Cx** [comment]
You should download the v12 version of Discord. V13 version does not work integrated for these codes.
